# Generated by Django 5.2.4 on 2025-08-06 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponsad',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='sell'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weaponsad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
