# Generated by Django 5.2.4 on 2025-08-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_weaponsad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponsad',
            name='price',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
