# Generated by Django 5.2.4 on 2025-08-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_weaponsad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponsad',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
