# Generated by Django 5.2.4 on 2025-08-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_weaponsad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponsad',
            name='image',
            field=models.ImageField(blank=True, default='WeaponZ/weapons-bg.jpg', null=True, upload_to='WeaponZ/'),
        ),
    ]
