# Generated by Django 5.2.4 on 2025-08-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_weaponsad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponsad',
            name='coins',
            field=models.IntegerField(default=1000),
        ),
    ]
