# Generated by Django 5.2.4 on 2025-08-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_weaponsad_coins_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
