# Generated by Django 5.2.4 on 2025-08-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponsad',
            name='image',
            field=models.ImageField(blank=True, default='WeaponZ/1.jpg', null=True, upload_to='WeaponZ/'),
        ),
    ]
