# Generated by Django 5.2.4 on 2025-08-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
    ]
